baseURL = "https://mer0x.github.io/techfuse/"
languageCode = "en-us"
title = "Tech Fuse"
theme = "PaperMod"

# Enable robots.txt and emojis
enableRobotsTXT = true
enableEmoji = true

# Add main menu items
[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

# Theme parameters
[params]
  # Site description
  description = "An AI-powered tech blog"
  
  # Default theme (auto, light, dark)
  defaultTheme = "auto"

  # Display settings
  ShowFeatured = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  

  # Enable search
  [params.assets]
    disableFingerprinting = true

  # Search configuration (important for search to work)
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Taxonomy settings
[taxonomies]
  tag = "tags"

# Markup settings for code highlighting 
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML in markdown

# Create search page
[outputs]
  home = ["HTML", "RSS", "JSON"]
